# Generated by Django 3.2 on 2022-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d', verbose_name='프로필 이미지'),
        ),
    ]
