# Generated by Django 3.2 on 2022-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220814_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='아이디'),
        ),
    ]
