# Generated by Django 3.2 on 2022-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default=1, max_length=10, verbose_name='성함'),
            preserve_default=False,
        ),
    ]
