# Generated by Django 3.2 on 2022-08-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='아이디'),
        ),
    ]
