# Generated by Django 3.2 on 2022-08-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='profile/%Y/%m/%d', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
    ]
