# Generated by Django 3.2 on 2022-08-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220820_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User<built-in function id>', max_length=20, unique=True, verbose_name='닉네임'),
        ),
    ]
