# Generated by Django 3.2 on 2022-08-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
