# Generated by Django 3.2 on 2022-08-21 00:17

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
